### ISSUE TITLE
[Typo] - Next and not Nuxt on title on file -  icon-components/react/index.md

### ISSUE THREAD

**Issue by Beethoven** [iconify/documentation#1]
On React page change Nuxt to Next

### Nuxt.js {#ssr} to Next
Component is compatible with Next.js.

**Comment by cyberalien** [comment]
Thanks a lot for reporting and sorry for delay.

For some reason I wasn't subscribed to issues in this repository and didn't get notification. Looks like this is no longer an issue, typo has been fixed.
